// apps/web/src/components/modules/auth/LoginView.tsx
'use client'

import { useState } from 'react'
import { signIn } from 'next-auth/react'
import { useRouter } from 'next/navigation'
import { useForm } from 'react-hook-form'
import { useLang } from '@/contexts/LangContext'
import { ChevronDown, ChevronUp, Leaf } from 'lucide-react'

interface LoginForm {
  email: string
  password: string
}

const TEST_ACCOUNTS = [
  { role: 'Admin', email: 'admin@esgchain.com', password: 'demo1234' },
  { role: 'Buyer', email: 'buyer@esgchain.com', password: 'demo1234' },
  { role: 'Sustain', email: 'sustain@esgchain.com', password: 'demo1234' },
  { role: 'Analyst', email: 'analyst@esgchain.com', password: 'demo1234' },
]

export function LoginView() {
  const { t } = useLang()
  const router = useRouter()
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)
  const [showTestAccounts, setShowTestAccounts] = useState(false)

  const { register, handleSubmit, setValue, formState: { errors } } = useForm<LoginForm>()

  const onSubmit = async (data: LoginForm) => {
    setLoading(true)
    setError('')
    try {
      const result = await signIn('credentials', {
        email: data.email,
        password: data.password,
        redirect: false,
      })
      if (result?.ok) {
        router.push('/dashboard')
      } else {
        setError(t('auth.loginError'))
      }
    } catch {
      setError(t('auth.loginError'))
    } finally {
      setLoading(false)
    }
  }

  const fillTestAccount = (email: string, password: string) => {
    setValue('email', email)
    setValue('password', password)
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-[#1a1714] via-[#1a4d3e] to-[#1a1714] flex items-center justify-center p-4">
      <div className="w-full max-w-md">
        {/* Logo card */}
        <div className="text-center mb-8">
          <div className="inline-flex items-center justify-center w-14 h-14 rounded-2xl bg-accent mb-4">
            <Leaf size={28} className="text-white" />
          </div>
          <h1 className="font-heading text-3xl font-bold text-white tracking-tight">ESG·Chain</h1>
          <p className="text-white/60 text-sm mt-2">{t('auth.loginSubtitle')}</p>
        </div>

        {/* Login Card */}
        <div className="bg-surface rounded-card shadow-modal p-8">
          <h2 className="font-heading font-semibold text-text-primary text-lg mb-6">{t('auth.loginTitle')}</h2>

          <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
            <div>
              <label className="label">{t('common.email')}</label>
              <input
                type="email"
                className={`input ${errors.email ? 'border-red-400' : ''}`}
                placeholder={t('auth.emailPlaceholder')}
                {...register('email', { required: true })}
              />
            </div>
            <div>
              <label className="label">{t('common.password')}</label>
              <input
                type="password"
                className={`input ${errors.password ? 'border-red-400' : ''}`}
                placeholder={t('auth.passwordPlaceholder')}
                {...register('password', { required: true })}
              />
            </div>

            {error && (
              <div className="bg-red-50 border border-red-200 rounded-btn px-3 py-2 text-sm text-red-600">
                {error}
              </div>
            )}

            <button
              type="submit"
              disabled={loading}
              className="w-full btn-primary py-2.5 text-base font-semibold disabled:opacity-60 disabled:cursor-not-allowed"
            >
              {loading ? t('auth.loggingIn') : t('auth.loginButton')}
            </button>
          </form>

          {/* Test accounts */}
          <div className="mt-6 border-t border-border pt-4">
            <button
              type="button"
              onClick={() => setShowTestAccounts(!showTestAccounts)}
              className="flex items-center gap-2 text-xs text-text-secondary hover:text-text-primary transition-colors w-full"
            >
              {showTestAccounts ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
              {t('auth.testAccounts')}
            </button>

            {showTestAccounts && (
              <div className="mt-3 space-y-1.5">
                {TEST_ACCOUNTS.map(account => (
                  <button
                    key={account.email}
                    type="button"
                    onClick={() => fillTestAccount(account.email, account.password)}
                    className="w-full text-left px-3 py-2 rounded-btn hover:bg-surface-2 transition-colors"
                  >
                    <span className="text-xs font-medium text-accent">{account.role}</span>
                    <span className="text-xs text-text-secondary ml-2">{account.email}</span>
                  </button>
                ))}
              </div>
            )}
          </div>
        </div>

        <p className="text-center text-white/40 text-xs mt-6">
          ESG·Chain &copy; {new Date().getFullYear()} · 永續供應鏈管理平台
        </p>
      </div>
    </div>
  )
}

// esgchain-web/src/views/auth/LoginView.vue
<template>
  <div class="login-page">
    <div class="login-card">
      <div class="login-header">
        <h1 class="login-title">ESG·Chain</h1>
        <p class="login-subtitle">永續供應鏈管理平台</p>
      </div>

      <!-- 測試帳號快速登入 -->
      <div class="demo-accounts">
        <div class="demo-label">測試帳號快速登入</div>
        <div class="demo-list">
          <button
            v-for="account in demoAccounts"
            :key="account.email"
            class="demo-btn"
            :disabled="authStore.isLoading"
            @click="quickLogin(account)"
          >
            <span class="demo-role">{{ account.role }}</span>
            <span class="demo-email">{{ account.email }}</span>
          </button>
        </div>
      </div>

      <div class="divider"><span>或手動輸入</span></div>

      <form class="login-form" @submit.prevent="handleLogin">
        <div class="form-group">
          <label for="email">Email</label>
          <input
            id="email"
            v-model="form.email"
            type="email"
            placeholder="your@email.com"
            required
            :disabled="authStore.isLoading"
          />
        </div>

        <div class="form-group">
          <label for="password">密碼</label>
          <input
            id="password"
            v-model="form.password"
            type="password"
            placeholder="••••••••"
            required
            :disabled="authStore.isLoading"
          />
        </div>

        <p v-if="errorMsg" class="error-msg">{{ errorMsg }}</p>

        <button type="submit" class="btn-login" :disabled="authStore.isLoading">
          <span v-if="authStore.isLoading">登入中...</span>
          <span v-else>登入</span>
        </button>
      </form>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import { useAuthStore } from '@/stores/auth'
import { useRouter } from 'vue-router'

export default defineComponent({
  name: 'LoginView',

  setup() {
    return { authStore: useAuthStore(), router: useRouter() }
  },

  data() {
    return {
      form: { email: '', password: '' },
      errorMsg: '',
      demoAccounts: [
        { role: '管理員', email: 'admin@esgchain.com', password: 'demo1234' },
        { role: '採購商', email: 'buyer@esgchain.com', password: 'demo1234' },
        { role: '永續長', email: 'sustain@esgchain.com', password: 'demo1234' },
        { role: '分析師', email: 'analyst@esgchain.com', password: 'demo1234' },
        { role: '供應商', email: 'supplier1@tpsteel.com.tw', password: 'demo1234' },
      ],
    }
  },

  methods: {
    async quickLogin(account: { email: string; password: string }) {
      this.form.email = account.email
      this.form.password = account.password
      await this.handleLogin()
    },
    async handleLogin() {
      this.errorMsg = ''
      try {
        const redirectPath = await this.authStore.login(this.form.email, this.form.password)
        this.router.push(redirectPath)
      } catch {
        this.errorMsg = '帳號或密碼錯誤，請重新輸入'
      }
    },
  },
})
</script>

<style scoped>
.login-page {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: var(--bg);
}

.login-card {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 12px;
  padding: 48px 40px;
  width: 100%;
  max-width: 420px;
}

.login-title {
  font-family: var(--font-title);
  font-size: 28px;
  color: var(--accent);
  margin-bottom: 4px;
}

.login-subtitle {
  color: var(--text-secondary);
  font-size: 14px;
  margin-bottom: 32px;
}

.form-group {
  margin-bottom: 20px;
}

.form-group label {
  display: block;
  font-size: 14px;
  font-weight: 500;
  margin-bottom: 6px;
  color: var(--text-primary);
}

.form-group input {
  width: 100%;
  padding: 10px 14px;
  border: 1px solid var(--border);
  border-radius: 6px;
  background: var(--surface);
  color: var(--text-primary);
  font-size: 14px;
  outline: none;
  transition: border-color 0.2s;
}

.form-group input:focus {
  border-color: var(--accent);
}

.error-msg {
  color: #dc2626;
  font-size: 13px;
  margin-bottom: 16px;
}

.btn-login {
  width: 100%;
  padding: 12px;
  background: var(--accent);
  color: #fff;
  border: none;
  border-radius: 6px;
  font-size: 15px;
  font-weight: 500;
  cursor: pointer;
  transition: background 0.2s;
}

.btn-login:hover:not(:disabled) {
  background: var(--accent-hover);
}

.btn-login:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

/* 測試帳號 */
.demo-accounts {
  margin-bottom: 20px;
}

.demo-label {
  font-size: 11px;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.06em;
  color: var(--text-secondary);
  margin-bottom: 8px;
}

.demo-list {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.demo-btn {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 8px 12px;
  background: var(--surface-2);
  border: 1px solid var(--border);
  border-radius: 6px;
  cursor: pointer;
  text-align: left;
  transition: all 0.15s;
  width: 100%;
}

.demo-btn:hover:not(:disabled) {
  background: #f0ede6;
  border-color: var(--accent);
}

.demo-btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.demo-role {
  font-size: 12px;
  font-weight: 600;
  color: var(--accent);
  min-width: 52px;
  background: rgba(26,77,62,0.08);
  padding: 2px 8px;
  border-radius: 99px;
  text-align: center;
}

.demo-email {
  font-size: 13px;
  color: var(--text-secondary);
  font-family: var(--font-mono);
}

/* 分隔線 */
.divider {
  display: flex;
  align-items: center;
  gap: 12px;
  margin: 20px 0;
  color: var(--text-secondary);
  font-size: 12px;
}

.divider::before,
.divider::after {
  content: '';
  flex: 1;
  height: 1px;
  background: var(--border);
}
</style>
